# Generated by Django 5.2.1 on 2025-05-30 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_votetopic_is_active_alter_vote_choice_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='votetopic',
            name='choices',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='votetopic',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vote',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='vote',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.votetopic'),
        ),
        migrations.AlterField(
            model_name='votetopic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votetopic',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
