# Generated by Django 5.2.1 on 2025-05-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_votetopic_choices_votetopic_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voted_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='votetopic',
            old_name='title',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='votetopic',
            name='description',
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vote',
            name='session_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='votetopic',
            name='choices',
            field=models.TextField(help_text='Comma-separated choices (e.g., Yes,No,Maybe)'),
        ),
    ]
