# Generated by Django 5.2.1 on 2025-05-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_voted_at_vote_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='justification',
            field=models.TextField(blank=True),
        ),
    ]
