# Generated by Django 5.2.1 on 2025-05-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vote_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='votetopic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
