# Generated by Django 5.2.1 on 2025-05-30 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_votetopic_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votetopic',
            old_name='choices',
            new_name='choice_texts',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.votetopic')),
            ],
        ),
    ]
